### ISSUE TITLE
configuring and running on Ubuntu 16.04

### ISSUE THREAD

**Issue by john-wilkes** [FabricAttachedMemory/Emulation#17] opened 2017-07-05 21:05 UTC
I am trying to run the FAM emulator on Ubuntu 16.04. Here's what I did to get a clean run of emulation_configure.bash.

Missing dependencies installed with "sudo apt-get install":
zlib1g-dev
gtk2-dev
libglib2.0-dev
dh-autoreconf
bison
flex
vmdebootstrap
libvirt-bin

I installed qemu 2.8.1.1 from source.

I made two minor changes to emulation_configure.bash:

1. add /usr/local/bin to PATH (for qemu-2.8.1.1)
   export PATH="/bin:/usr/local/bin:/usr/bin:/sbin:/usr/sbin"
 2. make 2.8.1.1 a verified qemu version
   declare -a VERIFIED_QEMU_VERSIONS=("2.6.0" "2.8.0" "2.8.1.1")

**Comment by john-wilkes** [comment] 2017-07-05 21:13
On Ubuntu 16.04, emulation_configure.bash runs without errors, but node_virsh.sh gets errors:

$ cd /tmp
$ ./node_virsh.sh define
[sudo] password for jwilkes: 
error: Failed to define domain from node01.xml
error: invalid argument: could not find capabilities for arch=x86_64 

error: Failed to define domain from node02.xml
error: invalid argument: could not find capabilities for arch=x86_64 

error: Failed to define domain from node04.xml
error: invalid argument: could not find capabilities for arch=x86_64 

error: Failed to define domain from node03.xml
error: invalid argument: could not find capabilities for arch=x86_64

**Comment by coloroco** [comment] 2017-07-07 16:16
I'm guessing the missing dependencies were because you built from source, so they didn't get pulled in via the dependencies of "apt-get install qemu-xxxx".    I also assume your addition of /usr/local/bin to PATH is for the location of your locally-built qemu?

The template node XML file was taken from a different version of qemu/libvirt.  First, what versions of libvirt packages did you install?  And are you sure they're "aware" of your custom qemu setup?

**Comment by coloroco** [comment] 2017-07-07 16:16
I'm setting up an Ubuntu system to try and reproduce your results.

**Comment by john-wilkes** [comment] 2017-07-07 16:24
I tried a fresh install of Debian 8.8 (Jessie) with these results:

apt-get install zlib1g-dev libglib2.0-dev dh-autoreconf bison flex vmdebootstrap libvirt-bin

zlib1g-dev:amd64      1:1.2.8.dfsg-2+b1
libglib2.0-dev             2.42.1-1+b1
dh-autoreconf            10
vmdebootstrap          0.5-2
libvirt-bin                   1.2.9-9+deb8u4

QEMU emulator version 2.8.1.1 installed from source (forced it to /usr/bin instead of /usr/local/bin)

jwilkes@jw:/tmp$ ./node_virsh.sh define
Domain node01 defined from node01.xml

Domain node04 defined from node04.xml

Domain node02 defined from node02.xml

Domain node03 defined from node03.xml

jwilkes@jw:/tmp$ ./node_virsh.sh start
error: Failed to start domain node01
error: unsupported configuration: guest and host CPU are not compatible: Host CPU does not provide required features: tsc-deadline, x2apic

error: Failed to start domain node04
error: unsupported configuration: guest and host CPU are not compatible: Host CPU does not provide required features: tsc-deadline, x2apic

error: Failed to start domain node02
error: unsupported configuration: guest and host CPU are not compatible: Host CPU does not provide required features: tsc-deadline, x2apic

error: Failed to start domain node03
error: unsupported configuration: guest and host CPU are not compatible: Host CPU does not provide required features: tsc-deadline, x2apic

**Comment by coloroco** [comment] 2017-07-07 16:43
I obviously didn't go "low enough" in picking a least-common-denominator CPU configuration in the node XML definition template....

**Comment by john-wilkes** [comment] 2017-07-07 17:03
I am using an AMD A10-7870K APU.

**Comment by john-wilkes** [comment] 2017-07-07 20:14
Looks like Ubuntu 17.04 has the required versions of packages; I get the same result as Debian Jessie. The emulation_configure.bash script runs with no errors, as does "node_virsh.sh define". But "node_virsh.sh start" gives the same error that I saw with Jessie:

error: Failed to start domain node01
error: the CPU is incompatible with host CPU: Host CPU does not provide required features: x2apic, tsc-deadline

**Comment by coloroco** [comment] 2017-07-07 21:11
> I am using an AMD A10-7870K APU.

Of course you are :-)  and so my choice from libvirt of a "least-common denominator" CPU, on my Intel-based system, might not work well.   I wonder if QEMU supports such a model (ie, for both AMD and INtel), or if I need to include a second XML file for AMD processor emulation?

**Comment by john-wilkes** [comment] 2017-07-07 22:41
I'm no expert, but QEMU has the "-cpu host" command line option...

**Comment by coloroco** [comment] 2017-07-10 13:30
We've gone back and forth on qemu-command line generation versus using libvirt and XML files.  Most of the feedback has preferred libvirt (with virt-manager) so I can't use that argument directly.

I thought I had encoded the "-cpu host" effect in the XML template, but obviously not.  Back to the docs....

**Comment by john-wilkes** [comment] 2017-07-10 14:49
Maybe "<cpu mode='host-model'> ?

host-passthrough
With this mode, the CPU visible to the guest should be exactly the same as the host CPU even in the aspects that libvirt does not understand. Though the downside of this mode is that the guest environment cannot be reproduced on different hardware.

**Comment by john-wilkes** [comment] 2017-07-10 14:51
host-model
The host-model mode is essentially a shortcut to copying host CPU definition from capabilities XML into domain XML. Since the CPU definition is copied just before starting a domain, exactly the same XML can be used on different hosts while still providing the best guest CPU each host supports. 

https://libvirt.org/formatdomain.html

**Comment by john-wilkes** [comment] 2017-07-10 22:54
In node_template.xml I set cpu mode='host-model' and I disabled x2apic and tsc-deadline (with "\<feature policy='disable' name='x2apic'\>" and "name='tsc-deadline'". Now node_virsh.sh complains that the GlobalNVM file can't be opened:

error: Failed to start domain node01
error: internal error: process exited while connecting to monitor: 2017-07-10T21:41:47.670851Z qemu-system-x86_64: -object memory-backend-file,mem-path=/var/lib/GlobalNVM,size=16G,id=FAM,share=on: can't open backing store /var/lib/GlobalNVM for guest RAM: Permission denied

**Comment by AustinHunting** [comment] 2017-07-11 16:06
On Ubuntu apparmor prevents the virtual machines from accessing the FAM backend file. 
Disabling apparmor and a reboot seems to fix the problem:
$ sudo systemctl stop apparmor.service
$ sudo update-rc.d -f apparmor remove
$ sudo chmod 666 /var/lib/GlobalNVM
$ sudo reboot

**Comment by john-wilkes** [comment] 2017-07-11 21:03
With apparmor disabled, qemu dies starting the first node (which happens to be node04). My guess is that this is due to Intel/AMD CPU incompatibilities in the xml file.

error: Failed to start domain node04
error: internal error: qemu unexpectedly closed the monitor: serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 127.0.0.1:0 -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -chardev spicevmc,id=charredir2,name=usbredir -device usb-redir,chardev=charredir2,id=redir2,bus=usb.0,port=4 -chardev spicevmc,id=charredir3,name=usbredir -device usb-redir,chardev=charredir3,id=redir3,bus=usb.0,port=5 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 -object memory-backend-file,mem-path=/var/lib/GlobalNVM,size=16G,id=FAM,share=on -device ivshmem-plain,memdev=FAM -msg time

**Comment by john-wilkes** [comment] 2017-07-11 22:21
I reverted to the original node_template.xml and added the two lines to disable x2apic and tsc-deadline, but it still fails.

$ diff ./node_template.xml-orig node_template.xml
19a20,21
\>     \<feature policy='disable' name='x2apic'/>
\>     \<feature policy='disable' name='tsc-deadline'/>

$ ./node_virsh.sh start
error: Failed to start domain node04
error: internal error: process exited while connecting to monitor: _size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -chardev spicevmc,id=charredir2,name=usbredir -device usb-redir,chardev=charredir2,id=redir2,bus=usb.0,port=4 -chardev spicevmc,id=charredir3,name=usbredir -device usb-redir,chardev=charredir3,id=redir3,bus=usb.0,port=5 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 -object memory-backend-file,mem-path=/var/lib/GlobalNVM,size=16G,id=FAM,share=on -device ivshmem-plain,memdev=FAM -msg timestamp=on
Domain id=17 is tainted: custom-argv
2017-07-11T23:04:21.453954Z qemu-system-x86_64: -object memory-backend-file,mem-path=/var/lib/GlobalNVM,size=16G,id=FAM,share=on: c


$ ls -l /var/lib/GlobalNVM 
-rw-rw-rw- 1 root root 17179869184 Jul 11 11:04 /var/lib/GlobalNVM

**Comment by tpot** [comment] 2017-08-01 00:39
I always run `./node_virsh.sh undefined` after messing with the node XML. Maybe this will fix your issue @john-wilkes?

I had the same apparmor and /var/lib/GlobalNVM problems which were fixed by uninstalling apparmor and running chmod.

**Comment by john-wilkes** [comment] 2017-08-01 21:32
The node_template.xml file is inherently Intel-centric because it was initially created with the "virsh dumpxml" command on an Intel-based machine. I created a new xml file on my AMD-based system and merged the FAME-specific entries from node_template.xml. With this new, AMD-oriented node_template.xml file, I was able to configure and run a 4-node FAME cluster.
I tried host-passthrough on the original node_template.xml, but it did not work on my AMD system, due to other stuff in the xml file.

**Comment by coloroco** [comment] 2017-08-01 21:43
I've got some changes pending that have multiple templates: a set for the node XML (AMD vs Intel) and another set for vmdebootstrap revisions.  I'm testing on a few more systems (Debian and Ubuntu) before I post the next round.

**Comment by coloroco** [comment] 2017-08-06 15:25
John and I have been working through email and I've posted an update to address his Ubuntu and AMD requirements.   While there will be more tweaks coming, I'm going to close this issue as it's served its purpose in highlighting the need for expansion.

**Closed as completed by coloroco** 2017-08-06 15:25 UTC
